repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.6.0'
  hooks:
  - id: check-yaml
    exclude: ^\.deploy/helm/app/templates/.*\.(yml|yaml)
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: '25.1.0'
  hooks:
  - id: black
    language_version: python3.11
- repo: https://github.com/pycqa/isort
  rev: '6.0.1'
  hooks:
  - id: isort
    name: isort (python)
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system  # the language of the hook - tells pre-commit how to install the hook.
      pass_filenames: true
      types: [python]
- repo: local
  hooks:
    - id: pyright
      name: pyright
      entry: python -m pyright
      language: system  # the language of the hook - tells pre-commit how to install the hook.
      pass_filenames: false
      types: [python]
